version: "3.7"
services:
  backend:
    build: .
    image: unitap-backend
    environment:
      - FIELD_KEY=${FIELD_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - BRIGHT_PRIVATE_KEY=${BRIGHT_PRIVATE_KEY}
      - DEBUG=${DEBUG}
      - SENTRY_DSN=${SENTRY_DSN}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
    expose:
      - 5678
    ports:
      - "5678:5678"
    depends_on:
      - database
      - redis
    volumes:
      - .:/code
  
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
  
  redis:
    image: redis:6.2-alpine
    restart: always
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local
